simple_erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='person_add'), name='home'),
    path('register/', include('survey.urls')),
]

survey/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.PersonCreateView.as_view(), name='person_add'),
    path('thanks/', views.success_view, name='success'),
    path('ajax/load-carmodels/', views.load_carmodels, name='ajax_load_carmodels'),
]

survey/models.py
from django.db import models
# from django.core.validators import RegexValidator
from phonenumber_field.modelfields import PhoneNumberField


class CarBrand(models.Model):
    name = models.CharField(max_length=30, blank=False)

    def __str__(self):
        return self.name


class CarModel(models.Model):
    carbrand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=False)

    def __str__(self):
        return self.name

class Year(models.Model):
    name = models.CharField(max_length=4)

    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=11, blank=False)
    carbrand = models.ForeignKey(CarBrand, on_delete=models.SET_NULL, null=True)
    carmodel = models.ForeignKey(CarModel, on_delete=models.SET_NULL, null=True)
    year = models.ForeignKey(Year, on_delete=models.SET_NULL, null=True )

    def __str__(self):
        return self.name

survey/forms.py
from django import forms
from .models import Person, CarModel, Year
from django.core import validators

class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ('name', 'carbrand', 'carmodel', 'year')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['carmodel'].queryset = CarModel.objects.none()

        if 'carbrand' in self.data:
            try:
                carbrand_id = int(self.data.get('carbrand'))
                self.fields['carmodel'].queryset = CarModel.objects.filter(carbrand_id=carbrand_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['carmodel'].queryset = self.instance.carbrand.carmodel_set.order_by('name')

survey/views.py
from django.shortcuts import *
from django.template import RequestContext
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from . import models
from .models import Person, CarModel
from . import forms
from .forms import PersonForm

class PersonCreateView(CreateView):
    model = Person
    form_class = forms.PersonForm
    success_url = reverse_lazy('success')

def load_carmodels(request):
    carbrand_id = request.GET.get('carbrand')
    carmodels = CarModel.objects.filter(carbrand_id=carbrand_id).order_by('name')
    return render(request, 'survey/carmodel_list.html', {'carmodels': carmodels})

def load_years(self, request):
    years = Year.objects.all()
    return render(request, 'survey/year_list.html', {'years': years})

def success_view(request):
    form = forms.PersonForm()
    if request.method == 'POST':
        form = forms.PersonForm(request.POST)
        if form.is_valid():
            print("Good")
    return render(request, 'survey/success_message.html', {'form': form})

survey/templates/survey/carmodel_list.html
<option value="">انتخاب مدل خودرو</option>
{% for carmodel in carmodels %}
<option value="{{ carmodel.pk }}">{{ carmodel.name }}</option>
{% endfor %}

survey/templates/survey/person_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <h2 class="text-center text_h2 mb-5">
        لطفا فرم زیر را تکمیل کنید
    </h2>

    <form method="POST" id="personForm" class="needs-validation text-right" data-carmodels-url="{% url 'ajax_load_carmodels' %}" novalidate>
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        <div class="mb-5">
            <div class="form-group mb-3 {% if field.errors %}error{% endif %}">
                <label for="id_name">شماره موبایل</label>
                {{ form.name|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="mb-3">
                <label for="id_carbrand">برند خودرو</label>
                {{ form.carbrand|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="mb-3">
                <label for="id_carmodel">مدل خودرو</label>
                {{ form.carmodel|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="mb-3">
                <label for="id_year">سال ساخت</label>
                {{ form.year|attr:"class:form-control"|attr:"required" }}
            </div>
        </div>
        <button class="btn buttn bg_black text_yellow px-5 py-3" type="submit">ارسال</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_carbrand").change(function () {
        var url = $("#personForm").attr("data-carmodels-url");
        var carbrandId = $(this).val();

        $.ajax({
            url: url,
            data: {
            'carbrand': carbrandId
            },
            success: function (data) {
            $("#id_carmodel").html(data);
            }
        });

        });
    </script>

{% endblock %}

survey/templates/survey/success_message.html
{% extends 'base.html' %}

{% block title %}Speedy Club{% endblock %}

{% block content %}
    <div class="text-right">
        <h2 class="text-right text_lg text_bold mb-3">
            از شما سپاسگزاریم :)
        </h2>
        <p class="text-right text_md mb-5">
            اطلاعات شما ثبت شد،
            <br/>
            منتظر تماس ما باشید.
        </p>
        <a class="btn buttn bg_black text_yellow px-5 py-3" href="{% url 'person_add' %}">
            بازگشت به فرم شرکت در جشنواره
        </a>
    </div>
{% endblock %}

survey/templates/survey/year_list.html
<option value="">سال ساخت</option>
{% for year in years %}
<option value="{{ year.pk }}">{{ year.name }}</option>
{% endfor %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="fa">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
        <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
        <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
        <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
        <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
        <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
        <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
        <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">

        <title>{% block title %}Speedy Club{% endblock %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
         integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
         integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous"/>
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'queries.css' %}" type="text/css">
    </head>

    <body>
        <header class="container-fluid p-0 m-0">
            <nav class="navbar navbar-expand-lg bg_black">
                <div class="container">
                    <a class="navbar-brand" href="#">
                        <img src="{% static 'images/logo.png' %}" height="64" alt="">
                    </a>
                    <ul class="navbar-nav">
                        <li class="nav-item px-3 d-none d-sm-inline">
                            <a class="nav-link text-white" href="#about">
                                درباره کمپین
                            </a>
                        </li>
                        <li class="nav-item px-3 d-none d-sm-inline">
                            <a class="nav-link text-white" href="https://sepahanoil.com/">
                                روغن موتور اسپیدی
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="">
                <img class="w-100 h-auto" src="{% static 'images/header.jpg' %}" alt="">
            </div>
        </header>
        
        <section class="container py mb">
            <h2 id="about" class="text-center text_h2 mb-5">
                جشنواره اسپیدی
            </h2>
            <p class="text-right text_sm px">
                از جشنواره «به اسپیدی اعتماد دارم» چیزی میدونید؟
                <br/>
                فقط کافیه فرم زیر رو تکمیل کنید که بهتون تا ۸۰٪ تخفیف خرید روغن موتور
                اسپیدی تعلق بگیره. علاوه بر این می تونید یکی از ۵ نفر برنده سرویس یکساله
                تعویض روغن موتور در خونه هم باشید!!!
            </p>
            <p class="text-right text_md text_bold px">
                این تازه اولشه. فرم رو تکمیل کنید و منتظر خبرهای جذابمون باشید.
            </p>
        </section>
        <section class="container-fluid bg_yellow py mb">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </section>

        <section class="container py mb">
            <h2 class="text-center text_h2 mb-5">
                زمان تعویض روغن موتور ارتباطی با کیلومتر کارکرد ندارد؟!
            </h2>
            <div id="15315842324338900">
                <script type="text/JavaScript"
                 src="https://www.aparat.com/embed/fsrtD?data[rnddiv]=15315842324338900&data[responsive]=yes"></script>
            </div>
        </section>

        <footer class="container-fluid bg_black py-5 m-0">
            <div class="container">
                <div class="row d-flex justify-content-center mb-5">
                    <div class="mx-4">
                        <a href="https://www.instagram.com/speedymotoroil/">
                            <i class="fab fa-instagram text-white text_md"></i>
                        </a>
                    </div>
                    <div class="mx-4">
                        <a href="https://twitter.com/itrustspeedy">
                            <i class="fab fa-twitter text-white text_md"></i>
                        </a>
                    </div>
                    <div class="mx-4">
                        <a href="https://www.facebook.com/speedy.motoroil.3">
                            <i class="fab fa-facebook text-white text_md"></i>
                        </a>
                    </div>
                    <div class="mx-4">
                        <a href="https://plus.google.com/u/0/112593516259396309980">
                            <i class="fab fa-google-plus-square text-white text_md"></i>
                        </a>
                    </div>
                </div>
                <div class="row d-flex justify-content-center">
                    <p class="text-center text_footer text-white">
                        تمامی حقوق این سایت متعلق به شرکت نفت سپاهان می باشد
                    </p>
                </div>
            </div>
        </footer>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
         integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
        <script src="{% static 'main.js' %}"></script>
    </body>
</html>